# Database configuration
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
cors:
  url: ${CORS_URL}

# GEMINI API KEY
gemini:
  api:
    key: ${GNKEY}
    uri: ${GNURI}

server:
  servlet:
    session:
      timeout: 30m